before_script:
  - git config --global http.proxy "${HTTP_PROXY}"
  - git config --global https.proxy "${HTTPS_PROXY}"
  - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@${GITLAB_SERVER}".insteadOf "https://${GITLAB_SERVER}"
  - export http_proxy="${HTTP_PROXY}"
  - export https_proxy="${HTTPS_PROXY}"
  - export no_proxy="${NO_PROXY}"

# the gta-unit-test is a container that remains alive across builds/tests.  clean up
# the gitlab url otherwise they accumulate and expire
after_script:
  - git config --global --unset url."https://gitlab-ci-token:${CI_JOB_TOKEN}@${GITLAB_SERVER}".insteadOf

stages:
  - build
  - test

build:gta:
  stage: build
  image: gta-devel
  tags:
    - gta
  script:
    - make
  artifacts:
    paths:
      - "out/tpmprovider.test"

test:
  stage: test
  image: gta-devel
  tags:
    - gta-unit-test
  script:
    - export CGO_CFLAGS_ALLOW="-f.*"
    - go test ./... -coverpkg=./... -coverprofile out/cover.out
    - go tool cover -func out/cover.out
    - go tool cover -html=out/cover.out -o out/cover.html
  artifacts:
    paths:
      - "out/cover.html"
